### ISSUE TITLE
periodicity at the TOF baseline

### ISSUE THREAD

**Issue by andreaheilrath** [skuschel/XFELMay2019#15]
Presumably there are several digitizers with different baselines reading out the voltages consecutively. This results in a periodic baseline, increasing the "noise". See picture, run 243.

That's one way to fix it, since the range i choose is empty

    fluctuations = []
    for n in range(0,6):
        fluctuations.extend(TOF[1][400000:500000])
    TOF[1] = TOF[1] - fluctuations

![Selection_048](https://user-images.githubusercontent.com/49402693/57497748-3ab63480-72d9-11e9-9992-973f2c6e987d.png)

**Comment by mrware91** [comment]
Problem resolved.
